language: python
python:
 - '3.5'
 - '3.6'
cache: pip
install:
 - pip install -r requirements.txt
 - pip install pycodestyle
 - imageio_download_bin ffmpeg
before_script:
 - pycodestyle --max-line-length=120 --show-source .
script: python -m pytest -W ignore::DeprecationWarning
